[#-- @ftlvariable name="plan" type="com.atlassian.bamboo.plan.Plan" --]
[#-- @ftlvariable name="repository" type="com.atlassian.bamboo.plugins.git.GitHubRepository" --]
[@ww.label labelKey='repository.github.repository' value=repository.repository /]
[@ww.label labelKey='repository.github.branch' value=repository.branch! hideOnNull=true /]
[@ww.label labelKey='repository.github.useShallowClones' value=repository.useShallowClones?string hideOnNull=true /]
[@ww.label labelKey='repository.github.useSubmodules' value=repository.useSubmodules?string hideOnNull=true /]
[@ww.label labelKey='repository.github.commandTimeout' value=repository.commandTimeout! hideOnNull=true /]
[@ww.label labelKey='repository.github.verbose.logs' value=repository.verboseLogs?string hideOnNull=true /]
