[#-- @ftlvariable name="plan" type="com.atlassian.bamboo.plan.Plan" --]
[#-- @ftlvariable name="plan.buildDefinition.repository" type="com.atlassian.bamboo.plugins.git.GitHubRepository" --]
[#assign repository=plan.buildDefinition.repository /]
[@ww.label labelKey='repository.github.repository' value='${repository.username}/${repository.repository}' /]
[@ww.label labelKey='repository.github.branch' value='${repository.branch!}' hideOnNull=true /]
[@ww.label labelKey='repository.git.useShallowClones' value='${repository.useShallowClones?string}' hideOnNull=true /]
